export let QuestionData = [
{ id: 1, question: "What is the capital city of Pakistan?", answer: "Islamabad." },
{ id: 2, question: "When did Pakistan gain independence?", answer: "14 August 1947." },
{ id: 3, question: "Who was the founder of Pakistan?", answer: "Quaid-e-Azam Muhammad Ali Jinnah." },
{ id: 4, question: "What is the national language of Pakistan?", answer: "Urdu." },
{ id: 5, question: "What is the largest province of Pakistan by area?", answer: "Balochistan." },
{ id: 6, question: "Which river is the longest in Pakistan?", answer: "The Indus River." },
{ id: 7, question: "What is the national animal of Pakistan?", answer: "Markhor." },
{ id: 8, question: "What is the national flower of Pakistan?", answer: "Jasmine." },
{ id: 9, question: "Which city is known as the City of Lights in Pakistan?", answer: "Karachi." },
{ id: 10, question: "What is the national sport of Pakistan?", answer: "Field Hockey." },
{ id: 11, question: "Which mountain is the highest in Pakistan?", answer: "K2." },
{ id: 12, question: "What is the currency of Pakistan?", answer: "Pakistani Rupee." },
{ id: 13, question: "Which city is the capital of Punjab province?", answer: "Lahore." },
{ id: 14, question: "Which sea borders Pakistan to the south?", answer: "The Arabian Sea." },
{ id: 15, question: "Who wrote the national anthem of Pakistan?", answer: "Hafeez Jalandhari." },
{ id: 16, question: "What is the national bird of Pakistan?", answer: "Chukar Partridge." },
{ id: 17, question: "Which Pakistani scientist won the Nobel Prize in Physics?", answer: "Dr. Abdus Salam." },
{ id: 18, question: "Which city is famous for the Faisal Mosque?", answer: "Islamabad." },
{ id: 19, question: "Which desert is the largest in Pakistan?", answer: "Thar Desert." },
{ id: 20, question: "What is the national tree of Pakistan?", answer: "Deodar Cedar." },
{ id: 21, question: "Which Pakistani city is known as the City of Gardens?", answer: "Lahore." },
{ id: 22, question: "Which province is Gwadar Port located in?", answer: "Balochistan." },
{ id: 23, question: "Which dam is the largest in Pakistan?", answer: "Tarbela Dam." },
{ id: 24, question: "What is the literacy rate roughly in Pakistan?", answer: "Around 60% (approximate)." },
{ id: 25, question: "Which Pakistani city is famous for sports goods manufacturing?", answer: "Sialkot." },
{ id: 26, question: "Which is the national drink of Pakistan?", answer: "Sugarcane Juice." },
{ id: 27, question: "Who was the first Prime Minister of Pakistan?", answer: "Liaquat Ali Khan." },
{ id: 28, question: "Which Pakistani province produces most of the wheat?", answer: "Punjab." },
{ id: 29, question: "Which famous valley is located in Khyber Pakhtunkhwa?", answer: "Swat Valley." },
{ id: 30, question: "Which Pakistani city hosts the Minar-e-Pakistan monument?", answer: "Lahore." },
{ id: 31, question: "Which is the largest city in Pakistan by population?", answer: "Karachi." },
{ id: 32, question: "What is the name of Pakistan's national airline?", answer: "Pakistan International Airlines (PIA)." },
{ id: 33, question: "Which historical site is known as the ancient city near Larkana?", answer: "Mohenjo-daro." },
{ id: 34, question: "Which Pakistani cricketer is known as the 'Sultan of Swing'?", answer: "Wasim Akram." },
{ id: 35, question: "Which pass connects Pakistan with Afghanistan near Khyber?", answer: "Khyber Pass." },
{ id: 36, question: "What is the national motto of Pakistan?", answer: "Faith, Unity, Discipline." },
{ id: 37, question: "Which Pakistani city is famous for truck art?", answer: "Karachi." },
{ id: 38, question: "Which is the largest airport in Pakistan?", answer: "Jinnah International Airport." },
{ id: 39, question: "Which Pakistani festival marks the end of Ramadan?", answer: "Eid-ul-Fitr." },
{ id: 40, question: "Which Pakistani province is known for the Kalash Valley?", answer: "Khyber Pakhtunkhwa." },
{ id: 41, question: "Which Pakistani leader is known as Quaid-e-Azam?", answer: "Muhammad Ali Jinnah." },
{ id: 42, question: "Which is the national mosque of Pakistan?", answer: "Faisal Mosque." },
{ id: 43, question: "Which Pakistani city is known as the City of Saints?", answer: "Multan." },
{ id: 44, question: "Which is the second highest mountain in the world located in Pakistan?", answer: "K2." },
{ id: 45, question: "Which Pakistani city is famous for its blue pottery?", answer: "Multan." },
{ id: 46, question: "Which Pakistani province has the largest population?", answer: "Punjab." },
{ id: 47, question: "Which lake is the largest in Pakistan?", answer: "Manchar Lake." },
{ id: 48, question: "Which Pakistani city is known for its historic Badshahi Mosque?", answer: "Lahore." },
{ id: 49, question: "Which Pakistani valley is famous for tourism and mountains?", answer: "Hunza Valley." },
{ id: 50, question: "Which Pakistani port city is the country's economic hub?", answer: "Karachi." }
];